#!/usr/bin/env python3
import argparse
import asyncio
import json
import re
import sys
from pathlib import Path
from urllib.parse import quote_plus

try:
    from playwright.async_api import async_playwright
except Exception as exc:
    raise SystemExit(f"Playwright chưa sẵn sàng: {exc}")

CDP_URL_DEFAULT = "http://127.0.0.1:9222"


def normalize_video_url(url: str) -> str:
    match = re.search(r"(https?://(?:www\.)?bilibili\.com/video/[A-Za-z0-9]+)", url or "")
    return match.group(1) if match else (url or "")


def cookie_netscape(cookies):
    lines = ["# Netscape HTTP Cookie File", "# Generated by OpenClaw Bilibili CDP"]
    for c in cookies:
        domain = c.get("domain") or ".bilibili.com"
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires") or 0)
        name = c.get("name") or ""
        value = c.get("value") or ""
        if name:
            lines.append("\t".join([domain, include_sub, path, secure, str(expires), name, value]))
    return "\n".join(lines) + "\n"


async def connect(cdp_url):
    p = await async_playwright().start()
    browser = await p.chromium.connect_over_cdp(cdp_url)
    context = browser.contexts[0] if browser.contexts else await browser.new_context()
    return p, browser, context


async def ensure_login_state(context):
    cookies = await context.cookies(["https://www.bilibili.com", "https://search.bilibili.com"])
    names = {c.get("name") for c in cookies}
    logged = bool(names & {"SESSDATA", "DedeUserID", "bili_jct"})
    return logged, cookies


async def cmd_cookies(args):
    p, browser, context = await connect(args.cdp)
    try:
        logged, cookies = await ensure_login_state(context)
        Path(args.out).write_text(cookie_netscape(cookies), encoding="utf-8")
        print(json.dumps({"ok": True, "logged_in": logged, "cookie_count": len(cookies), "cookies_path": args.out}, ensure_ascii=False))
        if not logged and args.require_login:
            raise SystemExit("BilibiliLoginRequired: Chrome CDP chưa có cookie login Bilibili. Hãy đăng nhập Bilibili trên Chrome thật rồi thử lại.")
    finally:
        await browser.close()
        await p.stop()


async def get_meta_from_page(page):
    title = await page.title()
    meta = {"title": title or "", "cover": "", "url": page.url}
    for selector, attr in [
        ("meta[property='og:title']", "content"),
        ("meta[name='title']", "content"),
    ]:
        try:
            value = await page.locator(selector).first.get_attribute(attr, timeout=1200)
            if value:
                meta["title"] = value.strip()
                break
        except Exception:
            pass
    for selector, attr in [
        ("meta[property='og:image']", "content"),
        ("meta[itemprop='image']", "content"),
        ("link[rel='image_src']", "href"),
    ]:
        try:
            value = await page.locator(selector).first.get_attribute(attr, timeout=1200)
            if value:
                if value.startswith("//"):
                    value = "https:" + value
                meta["cover"] = value.strip()
                break
        except Exception:
            pass
    text = ""
    try:
        text = (await page.locator("body").inner_text(timeout=2000))[:3000]
    except Exception:
        pass
    blocked_words = ["验证码", "登录", "请先登录", "安全验证", "captcha", "verify"]
    meta["needs_attention"] = any(word.lower() in text.lower() for word in blocked_words)
    return meta


async def cmd_meta(args):
    p, browser, context = await connect(args.cdp)
    try:
        logged, cookies = await ensure_login_state(context)
        page = await context.new_page()
        await page.goto(args.url, wait_until="domcontentloaded", timeout=args.timeout * 1000)
        await page.wait_for_timeout(2500)
        meta = await get_meta_from_page(page)
        meta.update({"ok": True, "logged_in": logged, "cookie_count": len(cookies), "source_url": args.url})
        Path(args.out).write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
        print(json.dumps(meta, ensure_ascii=False))
        if meta.get("needs_attention") and args.require_login:
            raise SystemExit("BilibiliLoginRequired: Bilibili đang yêu cầu login/captcha/verify trên Chrome thật.")
    finally:
        await browser.close()
        await p.stop()


async def cmd_search(args):
    p, browser, context = await connect(args.cdp)
    try:
        logged, _ = await ensure_login_state(context)
        page = await context.new_page()
        search_url = f"https://search.bilibili.com/all?keyword={quote_plus(args.keyword)}"
        await page.goto(search_url, wait_until="domcontentloaded", timeout=args.timeout * 1000)
        await page.wait_for_timeout(3500)
        items = await page.evaluate(
            r"""
            (limit) => {
              const out = [];
              const seen = new Set();
              for (const a of document.querySelectorAll('a[href*="/video/BV"], a[href*="/video/av"]')) {
                let href = a.href || a.getAttribute('href') || '';
                if (!href) continue;
                if (href.startsWith('//')) href = 'https:' + href;
                const m = href.match(/https?:\/\/(?:www\.)?bilibili\.com\/video\/[A-Za-z0-9]+/);
                if (!m) continue;
                href = m[0];
                if (seen.has(href)) continue;
                let title = (a.getAttribute('title') || '').replace(/\s+/g, ' ').trim();
                const card = a.closest('.video-list-item, .bili-video-card, .search-card, .video-item, li, div') || a;
                if (!title) {
                  const titleNode = card.querySelector('[title], .bili-video-card__info--tit, .title, h3');
                  title = ((titleNode && (titleNode.getAttribute('title') || titleNode.innerText)) || a.innerText || '').replace(/\s+/g, ' ').trim();
                }
                title = title.replace(/^\d+[\d.,万萬 triệu]*\s+\d+[\d.,万萬]*\s+\d{1,2}:\d{2}(?::\d{2})?\s*/i, '').trim();
                if (!title) title = href;
                seen.add(href);
                out.push({index: out.length + 1, title, url: href});
                if (out.length >= limit) break;
              }
              return out;
            }
            """,
            args.limit,
        )
        payload = {"ok": True, "logged_in": logged, "keyword": args.keyword, "count": len(items), "items": items}
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        if not items:
            raise SystemExit("BilibiliSearchEmpty: Không tìm thấy kết quả video. Nếu trang đang captcha/login, hãy xử lý trên Chrome thật.")
    finally:
        await browser.close()
        await p.stop()




def parse_episode_spec(spec: str):
    spec = (spec or "").strip()
    if not spec:
        return []
    out = []
    for part in re.split(r"[,，\s]+", spec):
        part = part.strip()
        if not part:
            continue
        match = re.match(r"^(\d{1,4})\s*(?:-|–|—|到|至|~)\s*(\d{1,4})$", part)
        if match:
            start, end = int(match.group(1)), int(match.group(2))
            step = 1 if end >= start else -1
            out.extend(range(start, end + step, step))
            continue
        match = re.search(r"\d{1,4}", part)
        if match:
            out.append(int(match.group(0)))
    dedup = []
    seen = set()
    for value in out:
        if value not in seen:
            seen.add(value)
            dedup.append(value)
    return dedup

def extract_episode_numbers(title: str):
    title = title or ""
    if re.search(r"\b序\b|《[^》]+》序|^序[:：]", title):
        return [0]
    patterns = [
        r"(?:第|^|》|[\s:：|｜])\s*(\d{1,4})\s*(?:集|话|話|章)",
        r"(?:第|^|》|[\s:：|｜])\s*(\d{1,4})\s*(?:-|–|—|至|到)\s*(\d{1,4})\s*(?:集|话|話|章)?",
    ]
    numbers = []
    for pattern in patterns:
        for match in re.finditer(pattern, title):
            if len(match.groups()) >= 2 and match.group(2):
                start, end = int(match.group(1)), int(match.group(2))
                if abs(end - start) <= 20:
                    step = 1 if end >= start else -1
                    numbers.extend(range(start, end + step, step))
            else:
                numbers.append(int(match.group(1)))
    # Also handle title like 邪神墨然 70： without 集 suffix, but avoid large duration/view numbers by requiring series marker.
    if not numbers and "邪神墨然" in title:
        match = re.search(r"邪神墨然[^\d]{0,8}(\d{1,4})\s*[:：]", title)
        if match:
            numbers.append(int(match.group(1)))
    dedup = []
    seen = set()
    for num in numbers:
        if num not in seen:
            seen.add(num)
            dedup.append(num)
    return dedup

def score_episode_item(item, keyword, requested, allow_compilation=False):
    title = item.get("title") or ""
    episodes = item.get("episodes") or []
    requested_set = set(requested)
    score = 0
    if keyword and keyword in title:
        score += 30
    if episodes and requested_set.intersection(episodes):
        score += 100
    if item.get("source") == "cdp_playlist":
        score += 25
    compilation_words = ("合集", "尊享", "一口气", "大合集", "VIP")
    is_compilation = any(word in title for word in compilation_words) or (episodes and len(episodes) >= 3)
    if is_compilation and not allow_compilation:
        score -= 80
    if requested and episodes:
        score -= min(30, abs(min(episodes) - min(requested)))
    return score

async def cmd_episodes(args):
    requested = parse_episode_spec(args.episodes)
    if not requested:
        raise SystemExit("BilibiliEpisodeSpecMissing: Thiếu số tập, ví dụ 0-3 hoặc 1,2,3.")
    allow_compilation = bool(re.search(r"合集|合辑|一口气|尊享|全集", args.keyword or "")) or bool(re.search(r"合集|合辑|一口气|尊享|全集", args.episodes or ""))
    p, browser, context = await connect(args.cdp)
    try:
        logged, _ = await ensure_login_state(context)
        page = None
        if args.url:
            page = await context.new_page()
            await page.goto(args.url, wait_until="domcontentloaded", timeout=args.timeout * 1000)
            await page.wait_for_timeout(2500)
        else:
            pages = []
            for existing in context.pages:
                try:
                    if "bilibili.com/video/" in existing.url:
                        pages.append(existing)
                except Exception:
                    pass
            if pages:
                # Prefer a page whose title/body contains the keyword.
                page = pages[0]
                for candidate in pages:
                    title = await candidate.title()
                    if args.keyword and args.keyword in title:
                        page = candidate
                        break
        if page is None:
            raise SystemExit("BilibiliPlaylistPageMissing: Không thấy tab video Bilibili trong Chrome CDP.")
        await page.wait_for_timeout(1000)
        dom = await page.evaluate(r"""
        () => {
          const norm = (u) => {
            if (!u) return '';
            if (u.startsWith('//')) return 'https:' + u;
            if (u.startsWith('/')) return 'https://www.bilibili.com' + u;
            return u;
          };
          const cleanVideo = (u) => {
            const m = norm(u).match(/https?:\/\/(?:www\.)?bilibili\.com\/video\/[A-Za-z0-9]+/);
            return m ? m[0] : '';
          };
          const bodyText = (document.body.innerText || '').replace(/\r/g, '');
          const items = [];
          const seen = new Set();
          const selectors = [
            '.video-pod a[href*="/video/"]',
            '.video-pod .simple-base-item',
            '.video-sections-content-list a[href*="/video/"]',
            '.base-video-sections a[href*="/video/"]',
            '.video-section-list a[href*="/video/"]',
            '.video-pod__item',
            '.pod-item'
          ];
          for (const selector of selectors) {
            for (const el of document.querySelectorAll(selector)) {
              const a = el.tagName === 'A' ? el : el.querySelector('a[href*="/video/"]');
              const href = cleanVideo((a && (a.getAttribute('href') || a.href)) || '');
              const text = (el.innerText || el.textContent || (a && a.getAttribute('title')) || '').replace(/\s+/g, ' ').trim();
              const key = href + '|' + text;
              if ((!href && !text) || seen.has(key)) continue;
              seen.add(key);
              items.push({url: href || location.href, title: text, duration: '', source: 'cdp_playlist_dom'});
            }
            if (items.length >= 3) break;
          }
          const state = window.__INITIAL_STATE__ || {};
          const stateSeen = new Set();
          const pushStateItem = (node) => {
            if (!node || typeof node !== 'object') return;
            const bvid = node.bvid || node.bv_id || (node.arc && node.arc.bvid) || '';
            const title = node.title || (node.arc && node.arc.title) || '';
            const duration = node.duration || (node.arc && node.arc.duration) || (node.page && node.page.duration) || '';
            if (bvid && title) {
              const url = 'https://www.bilibili.com/video/' + bvid;
              const key = url + '|' + title;
              if (!stateSeen.has(key)) {
                stateSeen.add(key);
                items.push({url, title, duration: String(duration || ''), source: 'cdp_playlist_state'});
              }
            }
          };
          const walk = (node, depth=0) => {
            if (!node || depth > 8) return;
            if (Array.isArray(node)) {
              for (const child of node) walk(child, depth + 1);
              return;
            }
            if (typeof node === 'object') {
              pushStateItem(node);
              for (const [key, value] of Object.entries(node)) {
                if (/section|episode|archives|list|item|ugc|season/i.test(key)) walk(value, depth + 1);
              }
            }
          };
          walk(state.sectionsInfo || state.videoData || state, 0);
          return {url: location.href, title: document.title, bodyText, items: items.slice(0, 360)};
        }
        """)
        raw_items = dom.get("items") or []
        # Bilibili sometimes renders playlist as plain body lines; parse those if DOM nodes are sparse.
        body_lines = [line.strip() for line in (dom.get("bodyText") or "").split("\n") if line.strip()]
        line_items = []
        for idx, line in enumerate(body_lines):
            if args.keyword and args.keyword not in line:
                continue
            if not ("集" in line or "序" in line):
                continue
            duration = ""
            if idx + 1 < len(body_lines) and re.match(r"^\d{1,2}:\d{2}(?::\d{2})?$", body_lines[idx + 1]):
                duration = body_lines[idx + 1]
            line_items.append({"url": "", "title": line, "duration": duration, "source": "cdp_playlist_text"})
        raw_items = sorted(raw_items, key=lambda item: 0 if item.get("source") == "cdp_playlist_state" else 1)
        all_items = []
        for item in raw_items + line_items:
            title = re.sub(r"\s+", " ", item.get("title") or "").strip()
            if not title:
                continue
            episodes = extract_episode_numbers(title)
            if not episodes:
                continue
            if args.keyword and args.keyword not in title and "邪神墨然" not in title:
                continue
            all_items.append({
                "episode": episodes[0] if len(episodes) == 1 else f"{episodes[0]}-{episodes[-1]}",
                "episodes": episodes,
                "title": title,
                "url": item.get("url") or "",
                "duration": item.get("duration") or "",
                "source": "cdp_playlist",
            })
        # Deduplicate by episode/title, prefer entries with URL, then text order.
        dedup = {}
        for item in all_items:
            key = (tuple(item["episodes"]), item["title"])
            if key not in dedup or (item.get("url") and not dedup[key].get("url")):
                dedup[key] = item
        all_items = list(dedup.values())
        matched = []
        for episode in requested:
            candidates = [item for item in all_items if episode in (item.get("episodes") or [])]
            candidates.sort(key=lambda item: score_episode_item(item, args.keyword, [episode], allow_compilation), reverse=True)
            if candidates:
                best = dict(candidates[0])
                best["requested_episode"] = episode
                best["confidence"] = max(0, min(100, score_episode_item(best, args.keyword, [episode], allow_compilation)))
                matched.append(best)
        missing = [episode for episode in requested if not any(item.get("requested_episode") == episode for item in matched)]
        payload = {
            "ok": bool(matched),
            "logged_in": logged,
            "keyword": args.keyword,
            "requested_episodes": requested,
            "allow_compilation": allow_compilation,
            "source": "cdp_playlist",
            "page_url": dom.get("url"),
            "page_title": dom.get("title"),
            "count": len(matched),
            "items": matched,
            "missing_episodes": missing,
            "message": "" if not missing else f"Không thấy tập {missing} trong playlist đang mở; không tự thay bằng tập mới/latest.",
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        if not matched:
            raise SystemExit(payload["message"] or "BilibiliEpisodeNotFound: Không thấy tập yêu cầu trong playlist đang mở.")
    finally:
        await browser.close()
        await p.stop()

async def cmd_channel(args):
    p, browser, context = await connect(args.cdp)
    try:
        logged, cookies = await ensure_login_state(context)
        page = None
        if args.url:
            page = await context.new_page()
            await page.goto(args.url, wait_until="domcontentloaded", timeout=args.timeout * 1000)
            await page.wait_for_timeout(2500)
        else:
            for existing in context.pages:
                try:
                    if "bilibili.com" in existing.url:
                        page = existing
                        break
                except Exception:
                    pass
            if page is None:
                raise SystemExit("BilibiliChannelNotFound: Không thấy tab Bilibili trong Chrome CDP.")
        payload = await page.evaluate(r"""
        () => {
          const norm = (u) => {
            if (!u) return '';
            if (u.startsWith('//')) return 'https:' + u;
            if (u.startsWith('/')) return 'https://www.bilibili.com' + u;
            return u;
          };
          const cleanSpace = (u) => {
            const m = norm(u).match(/https?:\/\/space\.bilibili\.com\/(\d+)/);
            return m ? 'https://space.bilibili.com/' + m[1] : '';
          };
          const currentSpace = cleanSpace(location.href);
          const textOf = (el) => ((el && (el.innerText || el.textContent || el.getAttribute('title'))) || '').replace(/\s+/g, ' ').trim();
          const headerName = textOf(document.querySelector('.h-name, .nickname, .user-name, .name, .up-name, .user-info .name'));
          if (currentSpace) {
            return {channel_url: currentSpace, channel_name: headerName || document.title.replace(/的个人空间.*/, '').replace(/个人主页.*/, '').trim(), page_url: location.href, page_title: document.title, candidates: []};
          }
          const candidates = [];
          const ownerSelectors = [
            '.up-info-container a[href*="space.bilibili.com"]',
            '.up-info a[href*="space.bilibili.com"]',
            '.video-owner a[href*="space.bilibili.com"]',
            '.members-info-container a[href*="space.bilibili.com"]',
            '.user-card a[href*="space.bilibili.com"]',
            'a.up-name[href*="space.bilibili.com"]',
            'a[href*="space.bilibili.com"]'
          ];
          for (const selector of ownerSelectors) {
            for (const a of document.querySelectorAll(selector)) {
              const url = cleanSpace(a.getAttribute('href') || a.href || '');
              if (!url) continue;
              const text = textOf(a);
              const rect = a.getBoundingClientRect();
              let score = 0;
              if (selector !== 'a[href*="space.bilibili.com"]') score += 100;
              if (text) score += 10;
              if (/bili_\d+/i.test(text)) score -= 60;
              if ((a.className || '').toString().match(/up|owner|name|author/i)) score += 20;
              if (rect.top >= 0 && rect.top < 420 && rect.left < 1500) score += 8;
              // Avoid top-right logged-in account links: usually near far right top and not in owner containers.
              if (rect.top >= 0 && rect.top < 120 && rect.left > window.innerWidth * 0.65 && selector === 'a[href*="space.bilibili.com"]') score -= 80;
              candidates.push({url, name: text, score, selector});
            }
          }
          const dedup = new Map();
          for (const c of candidates) {
            const old = dedup.get(c.url);
            if (!old || c.score > old.score) dedup.set(c.url, c);
          }
          const sorted = Array.from(dedup.values()).sort((a,b) => b.score - a.score);
          const best = sorted[0] || null;
          return {channel_url: best ? best.url : '', channel_name: best ? best.name : '', page_url: location.href, page_title: document.title, candidates: sorted.slice(0, 8)};
        }
        """)
        payload.update({"ok": bool(payload.get("channel_url")), "logged_in": logged, "cookie_count": len(cookies)})
        Path(args.out).write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        if not payload.get("channel_url"):
            raise SystemExit("BilibiliChannelNotFound: Không lấy được URL kênh/uploader từ trang Bilibili.")
    finally:
        await browser.close()
        await p.stop()

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cdp", default=CDP_URL_DEFAULT)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("cookies")
    p.add_argument("--out", required=True)
    p.add_argument("--require-login", action="store_true")
    p.set_defaults(func=cmd_cookies)

    p = sub.add_parser("meta")
    p.add_argument("url")
    p.add_argument("--out", required=True)
    p.add_argument("--timeout", type=int, default=30)
    p.add_argument("--require-login", action="store_true")
    p.set_defaults(func=cmd_meta)

    p = sub.add_parser("search")
    p.add_argument("keyword")
    p.add_argument("--limit", type=int, default=10)
    p.add_argument("--timeout", type=int, default=30)
    p.set_defaults(func=cmd_search)

    p = sub.add_parser("channel")
    p.add_argument("url", nargs="?", default="")
    p.add_argument("--out", required=True)
    p.add_argument("--timeout", type=int, default=30)
    p.set_defaults(func=cmd_channel)

    p = sub.add_parser("episodes")
    p.add_argument("keyword")
    p.add_argument("episodes")
    p.add_argument("--url", default="")
    p.add_argument("--timeout", type=int, default=30)
    p.set_defaults(func=cmd_episodes)

    args = parser.parse_args()
    asyncio.run(args.func(args))


if __name__ == "__main__":
    main()
