const API = "http://127.0.0.1:18793/api/bilibili/login/cookies";
const AUTH_COOKIES = new Set(["SESSDATA", "DedeUserID", "bili_jct"]);

function netscape(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by Auto Vietsub"];
  for (const cookie of cookies) {
    const domain = cookie.domain || ".bilibili.com";
    const prefix = cookie.httpOnly ? "#HttpOnly_" : "";
    lines.push([
      prefix + domain,
      cookie.hostOnly ? "FALSE" : "TRUE",
      cookie.path || "/",
      cookie.secure ? "TRUE" : "FALSE",
      String(Math.max(0, Math.floor(cookie.expirationDate || 0))),
      cookie.name,
      cookie.value,
    ].join("\t"));
  }
  return `${lines.join("\n")}\n`;
}

async function syncCookies() {
  const cookies = await chrome.cookies.getAll({domain: "bilibili.com"});
  if (!cookies.some((cookie) => AUTH_COOKIES.has(cookie.name))) return;
  const response = await fetch(API, {
    method: "POST",
    headers: {"Content-Type": "application/json"},
    body: JSON.stringify({text: netscape(cookies)}),
  });
  if (response.ok) {
    await chrome.action?.setBadgeText?.({text: "OK"});
    await chrome.action?.setBadgeBackgroundColor?.({color: "#16a34a"});
  }
}

chrome.runtime.onInstalled.addListener(syncCookies);
chrome.runtime.onStartup.addListener(syncCookies);
chrome.cookies.onChanged.addListener(({cookie}) => {
  if (cookie.domain.endsWith("bilibili.com")) syncCookies();
});
