import asyncio
from datetime import datetime, timezone
import os
from pathlib import Path
import shutil
import subprocess
import threading
import time
import uuid
from urllib.parse import urlsplit
import re

from .config import Settings
from .secrets import SecretStore, sanitize


AUTH_COOKIES = {"SESSDATA", "DedeUserID", "bili_jct"}
BILIBILI_VIDEO_PATH = re.compile(r"^/video/([A-Za-z0-9]+)/*$")
MAX_COOKIE_BYTES = 1024 * 1024
QR_SELECTORS = (
    ".login-scan-box img",
    ".qrcode-img",
    "[class*='qrcode'] img",
    "[class*='qr-code'] img",
    "[class*='qrcode'] canvas",
    "canvas",
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _domain_allowed(domain: str) -> bool:
    value = domain.lower().lstrip(".")
    return value == "bilibili.com" or value.endswith(".bilibili.com")

def normalize_video_url(url: str) -> str:
    try:
        parsed = urlsplit(str(url or "").strip())
    except ValueError:
        return ""
    if parsed.scheme.lower() not in {"http", "https"}:
        return ""
    try:
        port = parsed.port
    except ValueError:
        return ""
    if parsed.username or parsed.password or port not in {None, 80, 443}:
        return ""
    if (parsed.hostname or "").lower() not in {
        "bilibili.com",
        "www.bilibili.com",
        "m.bilibili.com",
    }:
        return ""
    match = BILIBILI_VIDEO_PATH.fullmatch(parsed.path)
    return f"https://www.bilibili.com/video/{match.group(1)}" if match else ""


def _parse_netscape(text: str) -> list[dict]:
    if len(text.encode("utf-8")) > MAX_COOKIE_BYTES:
        raise ValueError("cookie file exceeds 1 MiB")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "# Netscape HTTP Cookie File":
        raise ValueError("Netscape cookie header is required")
    cookies = []
    for line_number, raw in enumerate(lines[1:], start=2):
        line = raw.strip("\r")
        if not line:
            continue
        http_only = line.startswith("#HttpOnly_")
        if line.startswith("#") and not http_only:
            continue
        if http_only:
            line = line[len("#HttpOnly_") :]
        fields = line.split("\t")
        if len(fields) != 7:
            raise ValueError(f"malformed cookie line {line_number}")
        domain, include_subdomains, path, secure, expires, name, value = fields
        if not _domain_allowed(domain):
            raise ValueError(f"cookie line {line_number} has unsupported domain")
        if include_subdomains not in {"TRUE", "FALSE"}:
            raise ValueError(f"cookie line {line_number} has invalid domain flag")
        if secure not in {"TRUE", "FALSE"}:
            raise ValueError(f"cookie line {line_number} has invalid secure flag")
        if not path.startswith("/") or not name:
            raise ValueError(f"malformed cookie line {line_number}")
        try:
            expires_value = int(expires)
        except ValueError as exc:
            raise ValueError(f"cookie line {line_number} has invalid expiry") from exc
        cookies.append(
            {
                "domain": domain,
                "path": path,
                "secure": secure == "TRUE",
                "expires": expires_value,
                "name": name,
                "value": value,
                "http_only": http_only,
            }
        )
    if not cookies:
        raise ValueError("cookie file contains no Bilibili cookies")
    if not AUTH_COOKIES.intersection(cookie["name"] for cookie in cookies):
        raise ValueError("cookie file does not contain a Bilibili login marker")
    return cookies


def _netscape(cookies: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by Auto Vietsub"]
    for cookie in cookies:
        domain = str(cookie.get("domain") or ".bilibili.com")
        if not _domain_allowed(domain):
            continue
        name = str(cookie.get("name") or "")
        if not name:
            continue
        prefix = "#HttpOnly_" if cookie.get("httpOnly") else ""
        lines.append(
            "\t".join(
                (
                    prefix + domain,
                    "TRUE" if domain.startswith(".") else "FALSE",
                    str(cookie.get("path") or "/"),
                    "TRUE" if cookie.get("secure") else "FALSE",
                    str(max(0, int(cookie.get("expires") or 0))),
                    name,
                    str(cookie.get("value") or ""),
                )
            )
        )
    return "\n".join(lines) + "\n"


class BilibiliLogin:
    def __init__(self, settings: Settings, secret_store: SecretStore):
        self.settings = settings
        self.secret_store = secret_store
        self.cookie_path = settings.secrets_dir / "bilibili-cookies.txt"
        self.cdp_url = os.environ.get(
            "BILIBILI_CDP_URL",
            "http://127.0.0.1:9222",
        ).rstrip("/")
        self._lock = threading.Lock()
        self._thread = None
        self._qr = b""
        try:
            cookie_count = len(
                _parse_netscape(self.cookie_path.read_text(encoding="utf-8"))
            )
        except (OSError, UnicodeError, ValueError):
            cookie_count = 0
        self._status = {
            "state": "logged_in" if cookie_count else "logged_out",
            "logged_in": bool(cookie_count),
            "verified": False,
            "cookie_count": cookie_count,
            "qr_available": False,
            "error_code": "",
            "last_checked": _now(),
        }

    def status(self) -> dict:
        with self._lock:
            return dict(self._status)

    def _set(self, **values) -> None:
        with self._lock:
            self._status.update(values)
            self._status["last_checked"] = _now()

    def start(self) -> dict:
        with self._lock:
            if self._thread and self._thread.is_alive():
                return dict(self._status)
            self._qr = b""
            self._status.update(
                {
                    "state": "connecting",
                    "logged_in": False,
                    "qr_available": False,
                    "error_code": "",
                    "last_checked": _now(),
                }
            )
            self._thread = threading.Thread(
                target=self._run,
                name="bilibili-login",
                daemon=True,
            )
            self._thread.start()
            return dict(self._status)

    def qr_png(self) -> bytes:
        with self._lock:
            if not self._qr:
                raise FileNotFoundError("QR code is not available")
            return bytes(self._qr)

    def import_netscape(self, text: str) -> dict:
        cookies = _parse_netscape(str(text or ""))
        self._write_cookie_file(str(text))
        self._set(
            state="logged_in",
            logged_in=True,
            verified=False,
            cookie_count=len(cookies),
            qr_available=False,
            error_code="",
        )
        return self.status()

    def probe(self, url: str) -> dict:
        source = normalize_video_url(url)
        if not source:
            raise ValueError("invalid Bilibili video URL")
        try:
            _parse_netscape(self.cookie_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, ValueError) as exc:
            self._set(
                state="needs_attention",
                logged_in=False,
                verified=False,
                error_code="BilibiliCookieInvalid",
            )
            return {
                "ok": False,
                "verified": False,
                "error_code": "BilibiliCookieInvalid",
                "message": sanitize(exc),
            }
        try:
            result = subprocess.run(
                [
                    "yt-dlp",
                    "--cookies",
                    str(self.cookie_path),
                    "--dump-single-json",
                    "--skip-download",
                    "--no-warnings",
                    source,
                ],
                capture_output=True,
                text=True,
                timeout=45,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            code = "BilibiliProbeUnavailable"
            self._set(verified=False, error_code=code)
            return {
                "ok": False,
                "verified": False,
                "error_code": code,
                "message": sanitize(exc),
            }
        if result.returncode == 0:
            try:
                import json
                metadata = json.loads(result.stdout)
            except (TypeError, ValueError):
                metadata = {}
            self._set(
                state="logged_in",
                logged_in=True,
                verified=True,
                error_code="",
            )
            return {
                "ok": True,
                "verified": True,
                "source_url": source,
                "id": metadata.get("id") or "",
                "title": metadata.get("title") or "",
                "duration": metadata.get("duration"),
            }
        stderr = (result.stderr or "").lower()
        if any(marker in stderr for marker in ("captcha", "verify", "验证", "验证码", "人机")):
            code = "BilibiliCaptchaRequired"
            message = "Bilibili yêu cầu captcha hoặc xác minh."
        elif any(marker in stderr for marker in ("login", "cookie", "sessdata", "登录")):
            code = "BilibiliCookieRejected"
            message = "Cookie Bilibili bị từ chối hoặc hết hạn."
        elif any(marker in stderr for marker in ("private video", "unavailable", "not available", "视频不存在")):
            code = "BilibiliVideoUnavailable"
            message = "Video Bilibili không khả dụng."
        else:
            code = "BilibiliProbeFailed"
            message = "Không xác minh được quyền tải video Bilibili."
        self._set(verified=False, error_code=code)
        return {
            "ok": False,
            "verified": False,
            "error_code": code,
            "message": message,
        }

    def clear(self) -> dict:
        self.cookie_path.unlink(missing_ok=True)
        browser_root = self.settings.browser_dir.resolve()
        if browser_root.is_dir():
            for child in browser_root.iterdir():
                resolved = child.resolve()
                try:
                    resolved.relative_to(browser_root)
                except ValueError:
                    continue
                if child.is_symlink() or child.is_file():
                    child.unlink(missing_ok=True)
                elif child.is_dir():
                    shutil.rmtree(child)
        with self._lock:
            self._qr = b""
        self._set(
            state="logged_out",
            logged_in=False,
            verified=False,
            cookie_count=0,
            qr_available=False,
            error_code="",
        )
        return self.status()

    def _write_cookie_file(self, text: str) -> None:
        temporary = self.settings.secrets_dir / f".bilibili-{uuid.uuid4().hex}.tmp"
        temporary.write_text(text.rstrip("\n") + "\n", encoding="utf-8")
        try:
            os.chmod(temporary, 0o600)
        except OSError:
            pass
        try:
            os.replace(temporary, self.cookie_path)
        finally:
            temporary.unlink(missing_ok=True)

    def _run(self) -> None:
        try:
            asyncio.run(self._login())
        except Exception as exc:
            self._set(
                state="needs_attention",
                logged_in=False,
                qr_available=False,
                error_code="BilibiliCdpUnavailable",
                message=sanitize(exc),
            )

    async def _login(self) -> None:
        try:
            from playwright.async_api import async_playwright
        except ImportError as exc:
            raise RuntimeError("Playwright is not installed") from exc

        async with async_playwright() as playwright:
            browser = await playwright.chromium.connect_over_cdp(self.cdp_url)
            context = (
                browser.contexts[0]
                if browser.contexts
                else await browser.new_context()
            )
            await self._apply_imported_cookies(context)
            cookies = await self._bilibili_cookies(context)
            if self._logged_in(cookies):
                self._save_browser_cookies(cookies)
                self._set(
                    state="logged_in",
                    logged_in=True,
                    cookie_count=len(cookies),
                    qr_available=False,
                    error_code="",
                )
                return

            page = await context.new_page()
            try:
                await page.goto(
                    "https://passport.bilibili.com/login",
                    wait_until="domcontentloaded",
                    timeout=30000,
                )
                if await self._captcha(page):
                    self._set(
                        state="needs_attention",
                        error_code="BilibiliCaptchaRequired",
                    )
                    return
                qr = await self._capture_qr(page)
                if not qr:
                    self._set(
                        state="needs_attention",
                        error_code="BilibiliQrNotFound",
                    )
                    return
                with self._lock:
                    self._qr = qr
                self._set(
                    state="waiting_scan",
                    qr_available=True,
                    error_code="",
                )

                deadline = time.monotonic() + 180
                while time.monotonic() < deadline:
                    await page.wait_for_timeout(2000)
                    if await self._captcha(page):
                        self._set(
                            state="needs_attention",
                            qr_available=False,
                            error_code="BilibiliCaptchaRequired",
                        )
                        return
                    cookies = await self._bilibili_cookies(context)
                    if self._logged_in(cookies):
                        self._save_browser_cookies(cookies)
                        self._set(
                            state="logged_in",
                            logged_in=True,
                            cookie_count=len(cookies),
                            qr_available=False,
                            error_code="",
                        )
                        return
                    self._set(state="waiting_scan")
                self._set(
                    state="needs_attention",
                    qr_available=False,
                    error_code="BilibiliLoginTimeout",
                )
            finally:
                await page.close()

    async def _apply_imported_cookies(self, context) -> None:
        try:
            cookies = _parse_netscape(self.cookie_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, ValueError):
            return
        playwright_cookies = []
        for cookie in cookies:
            item = {
                "name": cookie["name"],
                "value": cookie["value"],
                "domain": cookie["domain"],
                "path": cookie["path"],
                "secure": cookie["secure"],
                "httpOnly": cookie["http_only"],
            }
            if cookie["expires"] > 0:
                item["expires"] = cookie["expires"]
            playwright_cookies.append(item)
        await context.add_cookies(playwright_cookies)

    @staticmethod
    async def _bilibili_cookies(context) -> list[dict]:
        return await context.cookies(
            ["https://www.bilibili.com", "https://passport.bilibili.com"]
        )

    @staticmethod
    def _logged_in(cookies: list[dict]) -> bool:
        return bool(AUTH_COOKIES.intersection(cookie.get("name") for cookie in cookies))

    def _save_browser_cookies(self, cookies: list[dict]) -> None:
        text = _netscape(cookies)
        parsed = _parse_netscape(text)
        self._write_cookie_file(text)
        self._set(cookie_count=len(parsed))

    @staticmethod
    async def _captcha(page) -> bool:
        if "captcha" in page.url.lower():
            return True
        try:
            text = (await page.locator("body").inner_text(timeout=1500)).lower()
        except Exception:
            return False
        return any(
            marker in text
            for marker in ("安全验证", "验证码", "captcha", "geetest")
        )

    @staticmethod
    async def _capture_qr(page) -> bytes:
        deadline = time.monotonic() + 20
        while time.monotonic() < deadline:
            for selector in QR_SELECTORS:
                locator = page.locator(selector).first
                try:
                    if await locator.is_visible(timeout=500):
                        return await locator.screenshot(type="png")
                except Exception:
                    continue
            await page.wait_for_timeout(500)
        return b""
