import asyncio
from datetime import datetime, timezone
import os
from pathlib import Path
import shutil
import threading
import time
import uuid

from .config import Settings
from .secrets import SecretStore, sanitize


AUTH_COOKIES = {"SESSDATA", "DedeUserID", "bili_jct"}
MAX_COOKIE_BYTES = 1024 * 1024
QR_SELECTORS = (
    ".login-scan-box img",
    ".qrcode-img",
    "[class*='qrcode'] img",
    "[class*='qr-code'] img",
    "[class*='qrcode'] canvas",
    "canvas",
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _domain_allowed(domain: str) -> bool:
    value = domain.lower().lstrip(".")
    return value == "bilibili.com" or value.endswith(".bilibili.com")


def _parse_netscape(text: str) -> list[dict]:
    if len(text.encode("utf-8")) > MAX_COOKIE_BYTES:
        raise ValueError("cookie file exceeds 1 MiB")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "# Netscape HTTP Cookie File":
        raise ValueError("Netscape cookie header is required")
    cookies = []
    for line_number, raw in enumerate(lines[1:], start=2):
        line = raw.strip("\r")
        if not line:
            continue
        http_only = line.startswith("#HttpOnly_")
        if line.startswith("#") and not http_only:
            continue
        if http_only:
            line = line[len("#HttpOnly_") :]
        fields = line.split("\t")
        if len(fields) != 7:
            raise ValueError(f"malformed cookie line {line_number}")
        domain, include_subdomains, path, secure, expires, name, value = fields
        if not _domain_allowed(domain):
            raise ValueError(f"cookie line {line_number} has unsupported domain")
        if include_subdomains not in {"TRUE", "FALSE"}:
            raise ValueError(f"cookie line {line_number} has invalid domain flag")
        if secure not in {"TRUE", "FALSE"}:
            raise ValueError(f"cookie line {line_number} has invalid secure flag")
        if not path.startswith("/") or not name:
            raise ValueError(f"malformed cookie line {line_number}")
        try:
            expires_value = int(expires)
        except ValueError as exc:
            raise ValueError(f"cookie line {line_number} has invalid expiry") from exc
        cookies.append(
            {
                "domain": domain,
                "path": path,
                "secure": secure == "TRUE",
                "expires": expires_value,
                "name": name,
                "value": value,
                "http_only": http_only,
            }
        )
    if not cookies:
        raise ValueError("cookie file contains no Bilibili cookies")
    if not AUTH_COOKIES.intersection(cookie["name"] for cookie in cookies):
        raise ValueError("cookie file does not contain a Bilibili login marker")
    return cookies


def _netscape(cookies: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by Auto Vietsub"]
    for cookie in cookies:
        domain = str(cookie.get("domain") or ".bilibili.com")
        if not _domain_allowed(domain):
            continue
        name = str(cookie.get("name") or "")
        if not name:
            continue
        prefix = "#HttpOnly_" if cookie.get("httpOnly") else ""
        lines.append(
            "\t".join(
                (
                    prefix + domain,
                    "TRUE" if domain.startswith(".") else "FALSE",
                    str(cookie.get("path") or "/"),
                    "TRUE" if cookie.get("secure") else "FALSE",
                    str(max(0, int(cookie.get("expires") or 0))),
                    name,
                    str(cookie.get("value") or ""),
                )
            )
        )
    return "\n".join(lines) + "\n"


class BilibiliLogin:
    def __init__(self, settings: Settings, secret_store: SecretStore):
        self.settings = settings
        self.secret_store = secret_store
        self.cookie_path = settings.secrets_dir / "bilibili-cookies.txt"
        self.cdp_url = os.environ.get(
            "BILIBILI_CDP_URL",
            "http://127.0.0.1:9222",
        ).rstrip("/")
        self._lock = threading.Lock()
        self._thread = None
        self._qr = b""
        self._status = {
            "state": "logged_in" if self.cookie_path.is_file() else "logged_out",
            "logged_in": self.cookie_path.is_file(),
            "cookie_count": 0,
            "qr_available": False,
            "error_code": "",
            "last_checked": _now(),
        }

    def status(self) -> dict:
        with self._lock:
            return dict(self._status)

    def _set(self, **values) -> None:
        with self._lock:
            self._status.update(values)
            self._status["last_checked"] = _now()

    def start(self) -> dict:
        with self._lock:
            if self._thread and self._thread.is_alive():
                return dict(self._status)
            self._qr = b""
            self._status.update(
                {
                    "state": "connecting",
                    "logged_in": False,
                    "qr_available": False,
                    "error_code": "",
                    "last_checked": _now(),
                }
            )
            self._thread = threading.Thread(
                target=self._run,
                name="bilibili-login",
                daemon=True,
            )
            self._thread.start()
            return dict(self._status)

    def qr_png(self) -> bytes:
        with self._lock:
            if not self._qr:
                raise FileNotFoundError("QR code is not available")
            return bytes(self._qr)

    def import_netscape(self, text: str) -> dict:
        cookies = _parse_netscape(str(text or ""))
        self._write_cookie_file(str(text))
        self._set(
            state="logged_in",
            logged_in=True,
            cookie_count=len(cookies),
            qr_available=False,
            error_code="",
        )
        return self.status()

    def clear(self) -> dict:
        self.cookie_path.unlink(missing_ok=True)
        browser_root = self.settings.browser_dir.resolve()
        if browser_root.is_dir():
            for child in browser_root.iterdir():
                resolved = child.resolve()
                try:
                    resolved.relative_to(browser_root)
                except ValueError:
                    continue
                if child.is_symlink() or child.is_file():
                    child.unlink(missing_ok=True)
                elif child.is_dir():
                    shutil.rmtree(child)
        with self._lock:
            self._qr = b""
        self._set(
            state="logged_out",
            logged_in=False,
            cookie_count=0,
            qr_available=False,
            error_code="",
        )
        return self.status()

    def _write_cookie_file(self, text: str) -> None:
        temporary = self.settings.secrets_dir / f".bilibili-{uuid.uuid4().hex}.tmp"
        temporary.write_text(text.rstrip("\n") + "\n", encoding="utf-8")
        try:
            os.chmod(temporary, 0o600)
        except OSError:
            pass
        try:
            os.replace(temporary, self.cookie_path)
        finally:
            temporary.unlink(missing_ok=True)

    def _run(self) -> None:
        try:
            asyncio.run(self._login())
        except Exception as exc:
            self._set(
                state="needs_attention",
                logged_in=False,
                qr_available=False,
                error_code="BilibiliCdpUnavailable",
                message=sanitize(exc),
            )

    async def _login(self) -> None:
        try:
            from playwright.async_api import async_playwright
        except ImportError as exc:
            raise RuntimeError("Playwright is not installed") from exc

        async with async_playwright() as playwright:
            browser = await playwright.chromium.connect_over_cdp(self.cdp_url)
            context = (
                browser.contexts[0]
                if browser.contexts
                else await browser.new_context()
            )
            await self._apply_imported_cookies(context)
            cookies = await self._bilibili_cookies(context)
            if self._logged_in(cookies):
                self._save_browser_cookies(cookies)
                self._set(
                    state="logged_in",
                    logged_in=True,
                    cookie_count=len(cookies),
                    qr_available=False,
                    error_code="",
                )
                return

            page = await context.new_page()
            try:
                await page.goto(
                    "https://passport.bilibili.com/login",
                    wait_until="domcontentloaded",
                    timeout=30000,
                )
                if await self._captcha(page):
                    self._set(
                        state="needs_attention",
                        error_code="BilibiliCaptchaRequired",
                    )
                    return
                qr = await self._capture_qr(page)
                if not qr:
                    self._set(
                        state="needs_attention",
                        error_code="BilibiliQrNotFound",
                    )
                    return
                with self._lock:
                    self._qr = qr
                self._set(
                    state="waiting_scan",
                    qr_available=True,
                    error_code="",
                )

                deadline = time.monotonic() + 180
                while time.monotonic() < deadline:
                    await page.wait_for_timeout(2000)
                    if await self._captcha(page):
                        self._set(
                            state="needs_attention",
                            qr_available=False,
                            error_code="BilibiliCaptchaRequired",
                        )
                        return
                    cookies = await self._bilibili_cookies(context)
                    if self._logged_in(cookies):
                        self._save_browser_cookies(cookies)
                        self._set(
                            state="logged_in",
                            logged_in=True,
                            cookie_count=len(cookies),
                            qr_available=False,
                            error_code="",
                        )
                        return
                    self._set(state="waiting_scan")
                self._set(
                    state="needs_attention",
                    qr_available=False,
                    error_code="BilibiliLoginTimeout",
                )
            finally:
                await page.close()

    async def _apply_imported_cookies(self, context) -> None:
        try:
            cookies = _parse_netscape(self.cookie_path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, ValueError):
            return
        playwright_cookies = []
        for cookie in cookies:
            item = {
                "name": cookie["name"],
                "value": cookie["value"],
                "domain": cookie["domain"],
                "path": cookie["path"],
                "secure": cookie["secure"],
                "httpOnly": cookie["http_only"],
            }
            if cookie["expires"] > 0:
                item["expires"] = cookie["expires"]
            playwright_cookies.append(item)
        await context.add_cookies(playwright_cookies)

    @staticmethod
    async def _bilibili_cookies(context) -> list[dict]:
        return await context.cookies(
            ["https://www.bilibili.com", "https://passport.bilibili.com"]
        )

    @staticmethod
    def _logged_in(cookies: list[dict]) -> bool:
        return bool(AUTH_COOKIES.intersection(cookie.get("name") for cookie in cookies))

    def _save_browser_cookies(self, cookies: list[dict]) -> None:
        text = _netscape(cookies)
        parsed = _parse_netscape(text)
        self._write_cookie_file(text)
        self._set(cookie_count=len(parsed))

    @staticmethod
    async def _captcha(page) -> bool:
        if "captcha" in page.url.lower():
            return True
        try:
            text = (await page.locator("body").inner_text(timeout=1500)).lower()
        except Exception:
            return False
        return any(
            marker in text
            for marker in ("安全验证", "验证码", "captcha", "geetest")
        )

    @staticmethod
    async def _capture_qr(page) -> bytes:
        deadline = time.monotonic() + 20
        while time.monotonic() < deadline:
            for selector in QR_SELECTORS:
                locator = page.locator(selector).first
                try:
                    if await locator.is_visible(timeout=500):
                        return await locator.screenshot(type="png")
                except Exception:
                    continue
            await page.wait_for_timeout(500)
        return b""
